typography_spectrum: 0.7870951560325921
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.691093745874241
  lightness: 0.4305713279172778
  saturation: 0.7653489767108113
  rhythmicContrast: 0.08801558474078774
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4314945135265589
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Karl Schönswetter
  email: radikarl@fea.st
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/94db6d40-a332-4966-b0b7-42692a1d2d6f.jpg
name: Karlender
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/dedcb044-77fd-4e1d-9a7e-88d9bb008d41.jpg
title: ''
description: ''
purpose: []
